language: node_js 
node_js: '12.0.0' # fuck this bug to generate empty file
branches:
  only:
    - source

cache: npm

install:
  - npm install -g hexo-cli
  - npm install 

before_script:
  - git config user.name 'wonderkun'
  - git config user.email 'dekunwang2014@gmail.com'
script: 
  # - hexo clean 
  - hexo generate

after_script:
  - cd ./public
  - git init 
  - git add . 
  - git commit -m "Travis CI auto deploy my blog."
  - git push --force "https://${GH_TOKEN}@github.com/wonderkun/wonderkun.github.io.git" master:master 
